import type { SOPStep, AgentConfig } from '../config'

// Re-export config types for convenience
export type { SOPStep, AgentConfig } from '../config'

/**
 * Agent role identifiers
 */
export type AgentRole = 'pm' | 'ta' | 'fe' | 'design' | 'qa'

/**
 * Task status in the execution pipeline
 */
export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'skipped'

/**
 * Execution priority levels
 */
export type Priority = 'low' | 'medium' | 'high' | 'critical'

/**
 * A single task to be executed by an agent
 */
export interface Task {
  readonly id: string
  readonly agent: AgentRole
  readonly action: string
  readonly inputs: ReadonlyArray<string>
  readonly expectedOutputs: ReadonlyArray<string>
  readonly parallelWith?: ReadonlyArray<string>
  readonly dependsOn?: ReadonlyArray<string>
  status: TaskStatus
  priority: Priority
  retryCount: number
  maxRetries: number
  startedAt?: Date
  completedAt?: Date
  error?: Error
}

/**
 * Result from an agent execution
 */
export interface AgentResult {
  readonly taskId: string
  readonly agent: AgentRole
  readonly success: boolean
  readonly outputs: Record<string, unknown>
  readonly artifacts?: ReadonlyArray<Artifact>
  readonly duration: number
  readonly tokenUsage?: TokenUsage
  readonly error?: AgentError
}

/**
 * Token usage tracking
 */
export interface TokenUsage {
  readonly inputTokens: number
  readonly outputTokens: number
  readonly totalTokens: number
  readonly estimatedCost: number
}

/**
 * Artifact produced by an agent
 */
export interface Artifact {
  readonly type: 'code' | 'file' | 'document' | 'test' | 'report'
  readonly name: string
  readonly path?: string
  readonly content?: string
}

/**
 * Agent execution error
 */
export interface AgentError {
  readonly code: string
  readonly message: string
  readonly recoverable: boolean
  readonly context?: Record<string, unknown>
}

/**
 * Shared execution context between agents
 */
export interface ExecutionContext {
  readonly workflowId: string
  readonly sopName: string
  readonly userRequest: string
  readonly projectPath: string
  readonly startedAt: Date
  data: Record<string, unknown>
  outputs: Record<string, unknown>
  artifacts: Artifact[]
  history: ExecutionHistoryEntry[]
}

/**
 * History entry for tracking execution flow
 */
export interface ExecutionHistoryEntry {
  readonly timestamp: Date
  readonly agent: AgentRole
  readonly action: string
  readonly status: TaskStatus
  readonly summary?: string
}

/**
 * Workflow execution state
 */
export interface WorkflowState {
  readonly id: string
  readonly sopName: string
  readonly status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'
  readonly currentStep: number
  readonly totalSteps: number
  readonly tasks: Task[]
  readonly context: ExecutionContext
  readonly startedAt: Date
  completedAt?: Date
  error?: AgentError
}

/**
 * Execution plan generated by PM
 */
export interface ExecutionPlan {
  readonly workflowId: string
  readonly sopName: string
  readonly tasks: Task[]
  readonly estimatedDuration?: number
  readonly criticalPath: string[]
}

/**
 * Agent execution options
 */
export interface AgentExecutionOptions {
  readonly config: AgentConfig
  readonly context: ExecutionContext
  readonly task: Task
  readonly timeout?: number
  readonly onProgress?: (progress: AgentProgress) => void
}

/**
 * Agent progress update
 */
export interface AgentProgress {
  readonly taskId: string
  readonly agent: AgentRole
  readonly phase: 'starting' | 'thinking' | 'executing' | 'completing'
  readonly message: string
  readonly percentage?: number
}

/**
 * Incident report (Apology Letter)
 */
export interface IncidentReport {
  readonly id: string
  readonly timestamp: Date
  readonly workflowId: string
  readonly agent: AgentRole
  readonly task: Task
  readonly rootCause: string
  readonly riskAnalysis: string
  readonly preventionStrategy: string
  readonly context: Record<string, unknown>
  readonly stackTrace?: string
}

/**
 * Orchestrator events
 */
export type OrchestratorEvent =
  | { type: 'workflow:start'; workflowId: string; sopName: string }
  | { type: 'workflow:complete'; workflowId: string; duration: number }
  | { type: 'workflow:fail'; workflowId: string; error: AgentError }
  | { type: 'task:start'; taskId: string; agent: AgentRole }
  | { type: 'task:complete'; taskId: string; result: AgentResult }
  | { type: 'task:fail'; taskId: string; error: AgentError }
  | { type: 'agent:progress'; progress: AgentProgress }
  | { type: 'incident:created'; report: IncidentReport }

/**
 * Event handler type
 */
export type OrchestratorEventHandler = (event: OrchestratorEvent) => void

/**
 * Create a new task from an SOP step
 */
export function createTaskFromStep(step: SOPStep, workflowId: string): Task {
  return {
    id: `${workflowId}-${step.order}-${step.agent}`,
    agent: step.agent,
    action: step.action,
    inputs: [...step.inputs],
    expectedOutputs: [...step.outputs],
    parallelWith: step.parallel ? [...step.parallel] : undefined,
    status: 'pending',
    priority: 'medium',
    retryCount: 0,
    maxRetries: 3,
  }
}

/**
 * Generate a unique workflow ID
 */
export function generateWorkflowId(): string {
  const timestamp = Date.now().toString(36)
  const random = Math.random().toString(36).substring(2, 8)
  return `wf-${timestamp}-${random}`
}
